### ISSUE TITLE
请尊重作者的劳动成果

### ISSUE THREAD

**Issue by sangcz** [dxlani/dxl-vue-imagesPreview#1]

**Comment by dxlani** [comment]
感谢作者的启蒙，那我就提几个小建议吧，一个是模态框背景最好是fixed的，滚动的情况下，absolute不适用，第二个是初始化的时候，大图没有显示出来，特别是ctrl+f5的时候，第三个，建议可以option里增加index(初始化显示第几张)，show(boolean)用于初始化显示控制，再次感谢作者的源代码
